#pragma checksum "..\..\Room3Window.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "49ADA0C4A937A9E6B0E85BF874B77B15C816BF55F68E482B37557992FE1F2D5E"
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using DreamTeam;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace DreamTeam {
    
    
    /// <summary>
    /// Room3Window
    /// </summary>
    public partial class Room3Window : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 10 "..\..\Room3Window.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid Numbers;
        
        #line default
        #line hidden
        
        
        #line 34 "..\..\Room3Window.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox MonitorCount;
        
        #line default
        #line hidden
        
        
        #line 35 "..\..\Room3Window.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox KeyBoardCount;
        
        #line default
        #line hidden
        
        
        #line 36 "..\..\Room3Window.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox SystemUnitCount;
        
        #line default
        #line hidden
        
        
        #line 37 "..\..\Room3Window.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox APrinterCount;
        
        #line default
        #line hidden
        
        
        #line 38 "..\..\Room3Window.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox SofaCount;
        
        #line default
        #line hidden
        
        
        #line 39 "..\..\Room3Window.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TableCount;
        
        #line default
        #line hidden
        
        
        #line 40 "..\..\Room3Window.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox ChairCount;
        
        #line default
        #line hidden
        
        
        #line 41 "..\..\Room3Window.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox RouterCount;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/DreamTeam;component/room3window.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\Room3Window.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.Numbers = ((System.Windows.Controls.DataGrid)(target));
            return;
            case 2:
            
            #line 17 "..\..\Room3Window.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Button_Click);
            
            #line default
            #line hidden
            return;
            case 3:
            
            #line 26 "..\..\Room3Window.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Ch_Click);
            
            #line default
            #line hidden
            return;
            case 4:
            
            #line 27 "..\..\Room3Window.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Tb_Click);
            
            #line default
            #line hidden
            return;
            case 5:
            
            #line 28 "..\..\Room3Window.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.So_Click);
            
            #line default
            #line hidden
            return;
            case 6:
            
            #line 29 "..\..\Room3Window.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Pr_Click);
            
            #line default
            #line hidden
            return;
            case 7:
            
            #line 30 "..\..\Room3Window.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Sy_Click);
            
            #line default
            #line hidden
            return;
            case 8:
            
            #line 31 "..\..\Room3Window.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Key_Click);
            
            #line default
            #line hidden
            return;
            case 9:
            
            #line 32 "..\..\Room3Window.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Mo_Click);
            
            #line default
            #line hidden
            return;
            case 10:
            
            #line 33 "..\..\Room3Window.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Ro_Click);
            
            #line default
            #line hidden
            return;
            case 11:
            this.MonitorCount = ((System.Windows.Controls.TextBox)(target));
            return;
            case 12:
            this.KeyBoardCount = ((System.Windows.Controls.TextBox)(target));
            return;
            case 13:
            this.SystemUnitCount = ((System.Windows.Controls.TextBox)(target));
            return;
            case 14:
            this.APrinterCount = ((System.Windows.Controls.TextBox)(target));
            return;
            case 15:
            this.SofaCount = ((System.Windows.Controls.TextBox)(target));
            return;
            case 16:
            this.TableCount = ((System.Windows.Controls.TextBox)(target));
            return;
            case 17:
            this.ChairCount = ((System.Windows.Controls.TextBox)(target));
            return;
            case 18:
            this.RouterCount = ((System.Windows.Controls.TextBox)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

